import { REPORTS_TYPES } from "../assets/tableData";

export const DRIVER_REPORT_TABLE_FIELDS = [
  {
    dataName: "Report ID",
    dataKey: "id",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver_reports",
  },
  {
    dataName: "Driver Id",
    dataKey: "driver_id",
    accessKey: "driver",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
  },
  {
    dataName: "Date and Time of report",
    dataKey: "date_time",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Report Type",
    dataKey: "type_of_report",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: REPORTS_TYPES,
  },
  {
    dataName: "Truck Number",
    dataKey: "truck_number",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Trailer Number",
    dataKey: "trailer_number",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Description",
    dataKey: "description",
    sort: false,
    show: true,
    date: false,
  },
  {
    dataName: "Steps Taken",
    dataKey: "steps_taken",
    sort: false,
    show: true,
    date: false,
  },
];
