import {
  STATUS_CHOICES,
  IMMIGRATION_STATUS,
  CANADIAN_PROVINCES,
  UPDATE_STATUS_CHOICES,
  TERMINAL_CHOICES,
  DRIVERTYPE_CHOICES,
} from "../assets/tableData";

export const DRIVERS_TABLE_FIELDS_REPORT = [
  {
    dataName: "Driver ID",
    dataKey: "driver_id",
    sort: true,
    show: false,
    date: false,
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "Status Note",
    dataKey: "status_note",
    sort: true,
    show: false,
    date: false,
  },
  {
    dataName: "Update Status",
    dataKey: "update_status",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: UPDATE_STATUS_CHOICES,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Phone Number",
    dataKey: "phone_number",
    sort: true,
    show: true,
    date: false,
    copyable: true,
    searchable: true,
  },
  {
    dataName: "Email",
    dataKey: "email",
    sort: true,
    show: true,
    date: false,
    copyable: true,
  },
  {
    dataName: "Emergency Contact",
    dataKey: "emergency_contact",
    sort: true,
    show: true,
    date: false,
  },
  {
    dataName: "Emergency Phone",
    dataKey: "emergency_phone",
    sort: true,
    show: true,
    date: false,
    copyable: true,
  },
  {
    dataName: "Date of Birth",
    dataKey: "date_of_birth",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Immigration Status",
    dataKey: "immigration_status",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: IMMIGRATION_STATUS,
  },
  {
    dataName: "Routes",
    dataKey: "routes",
    sort: false,
    show: true,
    date: false,
    routes: true,
  },
  {
    dataName: "Terminal",
    dataKey: "terminal",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: TERMINAL_CHOICES,
  },
  {
    dataName: "Driver Type",
    dataKey: "driver_type",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: DRIVERTYPE_CHOICES,
  },
  {
    dataName: "Current USA driver",
    dataKey: "eligible_to_enter_usa",
    sort: false,
    show: true,
    date: false,
  },
  {
    dataName: "Social Insurance Number",
    dataKey: "sin.number",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "sin.file",
  },
  {
    dataName: "Class 1 License Issue Date",
    dataKey: "class1_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Class 1 Miles Driven Total",
    dataKey: "miles_driven_total",
    sort: true,
    show: false,
    date: false,
  },
  {
    dataName: "Date Available To Start",
    dataKey: "date_available",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Driver's License Number",
    dataKey: "licenses.dl_number",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkField: "licenses.file",
    searchable: true,
  },
  {
    dataName: "DL Province",
    dataKey: "licenses.dl_province",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: CANADIAN_PROVINCES,
  },
  {
    dataName: "DL Expiration Date",
    dataKey: "licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Abstract Issue Date",
    dataKey: "abstracts.issue_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "abstracts.file",
  },
  {
    dataName: "Application Date",
    dataKey: "application_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Criminal Records",
    dataKey: "criminal_records.file",
    sort: false,
    show: false,
    date: false,
    isLink: true,
    linkField: "criminal_records.file",
  },
  {
    dataName: "Road Tests Issue Date",
    dataKey: "road_tests.issue_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "road_tests.file",
  },
  {
    dataName: "Passport",
    dataKey: "passports.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "passports.file",
  },
  {
    dataName: "US Visa",
    dataKey: "us_visas.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "us_visas.file",
  },
  {
    dataName: "Immigration Document Expiry Date",
    dataKey: "immigration_doc.expiry_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "immigration_doc.file",
  },
  {
    dataName: "Log Books",
    dataKey: "log_books.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "log_books.file",
  },
  {
    dataName: "Hiring Date",
    dataKey: "hiring_date",
    sort: true,
    show: false,
    date: true,
  },
  {
    dataName: "Consent to Personal Investigation",
    dataKey: "consents.file",
    sort: false,
    show: false,
    date: false,
    isLink: true,
    linkField: "consents.file",
  },
  {
    dataName: "Remarks Comments",
    dataKey: "remarks_comments",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "File Box Number",
    dataKey: "file_box_number",
    sort: true,
    show: false,
    date: false,
  },
  {
    dataName: "TDG Cards Expiry Date",
    dataKey: "tdg_cards.expiry_date",
    sort: true,
    show: false,
    date: true,
    isLink: true,
    linkField: "tdg_cards.file",
  },
  {
    dataName: "Good To Go Cards Expiry Date",
    dataKey: "good_to_go_cards.expiry_date",
    sort: true,
    show: false,
    date: true,
    isLink: true,
    linkField: "good_to_go_cards.file",
  },
  {
    dataName: "Certificates of Violations Issue Date",
    dataKey: "certificates_of_violations.issue_date",
    sort: true,
    show: false,
    date: false,
    isLink: true,
    linkField: "certificates_of_violations.file",
  },
  {
    dataName: "Annual Performance Review Date",
    dataKey: "annual_performance_reviews.date_of_review",
    sort: true,
    show: false,
    date: true,
    isLink: true,
    linkField: "annual_performance_reviews.file",
  },
  {
    dataName: "Winter Courses Completion Date",
    dataKey: "winter_courses.date_of_completion",
    sort: true,
    show: false,
    date: true,
    isLink: true,
    linkField: "winter_courses.file",
  },
  {
    dataName: "Reference Checks",
    dataKey: "reference_checks.company",
    sort: true,
    show: false,
    date: false,
    isLink: true,
    linkField: "reference_checks.file",
  },
  {
    dataName: "Additional Training Certificates",
    dataKey: "certificates_additional_training.file",
    sort: false,
    show: false,
    date: false,
    isLink: true,
    linkField: "certificates_additional_training.file",
  },
  {
    dataName: "Accidents History",
    dataKey: "accidents_history",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "Traffic Convictions",
    dataKey: "traffic_convictions",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "Denied License",
    dataKey: "denied_license",
    sort: false,
    show: true,
    date: false,
  },
  {
    dataName: "Denied License Reason",
    dataKey: "denied_license_reason",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "License Suspended or Revoked",
    dataKey: "license_suspended_or_revoked",
    sort: false,
    show: true,
    date: false,
  },
  {
    dataName: "License Suspension or Revocation Reason",
    dataKey: "suspension_or_revocation_reason",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "Date of Leaving",
    dataKey: "date_of_leaving",
    sort: true,
    show: false,
    date: true,
  },
  {
    dataName: "Reason for Leaving",
    dataKey: "reason_for_leaving",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "LCV Certified",
    dataKey: "lcv_certified",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "CD Driver",
    dataKey: "cp_driver",
    sort: false,
    show: false,
    date: false,
  },
  {
    dataName: "Void Check",
    dataKey: "void_check.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "void_check.file",
  },
  {
    dataName: "Incorporation Docs",
    dataKey: "incorp_docs.number",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkField: "incorp_docs.file",
  },
  {
    dataName: "GST Docs",
    dataKey: "gst_docs.number",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkField: "gst_docs.file",
  },
  {
    dataName: "Driver Prescreenings",
    dataKey: "driver_prescreenings.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "driver_prescreenings.file",
  },
  {
    dataName: "Knowledge Test",
    dataKey: "knowledge_tests.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "knowledge_tests.file",
  },
  {
    dataName: "Pre-hire quizzes",
    dataKey: "prehire_quizes.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "prehire_quizes.file",
  },
  {
    dataName: "LCV Certificate Expiry Date",
    dataKey: "lcv_certificates.expiry_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "lcv_certificates.file",
  },
  {
    dataName: "LCV License Expiry Date",
    dataKey: "lcv_licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "lcv_licenses.file",
  },
  {
    dataName: "Abstract Request Form",
    dataKey: "abstract_request_forms.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "abstract_request_forms.file",
  },
  {
    dataName: "Driver Memos",
    dataKey: "driver_memos.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "driver_memos.file",
  },
  {
    dataName: "Employment Contract",
    dataKey: "employment_contracts.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "employment_contracts.file",
  },
  {
    dataName: "GTG Quizzes",
    dataKey: "gtg_quizes.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "gtg_quizes.file",
  },
  {
    dataName: "Tax Papers Issue Date",
    dataKey: "tax_papers.issue_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "tax_papers.file",
  },
  {
    dataName: "Mentor Forms",
    dataKey: "mentor_forms.file",
    sort: false,
    show: true,
    date: false,
    isLink: true,
    linkField: "mentor_forms.file",
  },
  {
    dataName: "PDIC Certificate Expiry Date",
    dataKey: "pdic_certificates.expiry_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "pdic_certificates.file",
  },
  {
    dataName: "Driver Statements Issue Date",
    dataKey: "driver_statements.issue_date",
    sort: true,
    show: true,
    date: true,
    isLink: true,
    linkField: "driver_statements.file",
  },
];

export const DRIVERS_TABLE_FIELDS_RECRUITING = [
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Phone Number",
    dataKey: "phone_number",
    sort: true,
    show: true,
    date: false,
    copyable: true,
    searchable: true,
  },
  {
    dataName: "Email",
    dataKey: "email",
    sort: true,
    show: true,
    date: false,
    copyable: true,
  },
  {
    dataName: "Application Date",
    dataKey: "application_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Date of Birth",
    dataKey: "date_of_birth",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Immigration Status",
    dataKey: "immigration_status",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: IMMIGRATION_STATUS,
  },
  {
    dataName: "Routes",
    dataKey: "routes",
    sort: false,
    show: true,
    routes: true,
  },
  {
    dataName: "Date Available To Start",
    dataKey: "date_available",
    sort: true,
    show: true,
    date: true,
  },
];

export const DRIVERS_TABLE_FIELDS_SAFETY = [
  {
    dataName: "Driver ID",
    dataKey: "driver_id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "Status Note",
    dataKey: "status_note",
    sort: true,
    show: true,
    date: false,
  },
  {
    dataName: "Phone Number",
    dataKey: "phone_number",
    sort: true,
    show: true,
    date: false,
    copyable: true,
    searchable: true,
  },
  {
    dataName: "Email",
    dataKey: "email",
    sort: true,
    show: true,
    date: false,
    copyable: true,
  },
  {
    dataName: "Date of Birth",
    dataKey: "date_of_birth",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Hiring Date",
    dataKey: "hiring_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Driver's License Number",
    dataKey: "licenses.dl_number",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "DL Province",
    dataKey: "licenses.dl_province",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: CANADIAN_PROVINCES,
  },
  {
    dataName: "DL Expiration Date",
    dataKey: "licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
  },
];

export const DRIVERS_TABLE_DOCUMENTS_EXPIRING = [
  {
    dataName: "Driver ID",
    dataKey: "driver_id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "Update Status",
    dataKey: "update_status",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: UPDATE_STATUS_CHOICES,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "DL Expiration Date",
    dataKey: "licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
  },
  {
    dataName: "Immigration Document Expiry Date",
    dataKey: "immigration_doc.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "immigration_doc.file",
  },
  {
    dataName: "TDG Cards Expiry Date",
    dataKey: "tdg_cards.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "tdg_cards.file",
  },
  {
    dataName: "Good To Go Cards Expiry Date",
    dataKey: "good_to_go_cards.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "good_to_go_cards.file",
  },
  {
    dataName: "LCV License Expiry Date",
    dataKey: "lcv_licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "lcv_licenses.file",
  },
  {
    dataName: "PDIC Certificate Expiry Date",
    dataKey: "pdic_certificates.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "pdic_certificates.file",
  },
];

export const DRIVERS_TABLE_TO_BE_REVIEWED_BY_SAFETY = [
  {
    dataName: "Driver ID",
    dataKey: "driver_id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "Update Status",
    dataKey: "update_status",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: UPDATE_STATUS_CHOICES,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
    searchable: true,
  },
  {
    dataName: "DL Expiration Date",
    dataKey: "licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
  },
  {
    dataName: "Immigration Document Expiry Date",
    dataKey: "immigration_doc.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "immigration_doc.file",
  },
  {
    dataName: "TDG Cards Expiry Date",
    dataKey: "tdg_cards.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "tdg_cards.file",
  },
  {
    dataName: "Good To Go Cards Expiry Date",
    dataKey: "good_to_go_cards.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "good_to_go_cards.file",
  },
  {
    dataName: "LCV License Expiry Date",
    dataKey: "lcv_licenses.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "lcv_licenses.file",
  },
  {
    dataName: "PDIC Certificate Expiry Date",
    dataKey: "pdic_certificates.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "pdic_certificates.file",
  },
];
