import {
  EQUIPMENT_STATUS_CHOICES,
  EQUIPMENT_TYPE_CHOICES,
  TERMINAL_CHOICES,
} from "../assets/tableData";

export const EQUIPMENT_TABLE_FIELDS = [
  {
    dataName: "Unit Number",
    dataKey: "unit_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "equipment",
    searchable: true,
  },
  {
    dataName: "Plate Number",
    dataKey: "equipment_license_plates.plate_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "equipment",
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: EQUIPMENT_STATUS_CHOICES,
  },
  {
    dataName: "VIN",
    dataKey: "vin",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Equipment Type",
    dataKey: "equipment_type",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: EQUIPMENT_TYPE_CHOICES,
  },
  {
    dataName: "Safety Expiry Date",
    dataKey: "equipment_safety_docs.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "equipment_safety_docs.file",
  },
  {
    dataName: "Terminal",
    dataKey: "terminal",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: TERMINAL_CHOICES,
  },
  {
    dataName: "Remarks",
    dataKey: "remarks",
    sort: true,
    show: true,
    date: false,
  },
];
