import { STATUS_CHOICES } from "../assets/tableData";

export const OFFICE_TABLE_FIELDS_SAFETY = [
  {
    dataName: "Employee ID",
    dataKey: "employee_id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "First Name",
    dataKey: "first_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "employee",
    searchable: true,
  },
  {
    dataName: "Last Name",
    dataKey: "last_name",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "employee",
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: STATUS_CHOICES,
  },
  {
    dataName: "Status Note",
    dataKey: "status_note",
    sort: true,
    show: true,
    date: false,
  },
  {
    dataName: "Phone Number",
    dataKey: "phone_number",
    sort: true,
    show: true,
    date: false,
    copyable: true,
    searchable: true,
  },
  {
    dataName: "Email",
    dataKey: "email",
    sort: true,
    show: true,
    date: false,
    copyable: true,
  },
  {
    dataName: "Date of Birth",
    dataKey: "date_of_birth",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Hiring Date",
    dataKey: "hiring_date",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Application Date",
    dataKey: "application_date",
    sort: true,
    show: true,
    date: true,
  },
];
