import {
  TERMINAL_CHOICES,
  TRUCK_STATUS_CHOICES,
  VEHICLE_TYPE_CHOICES,
} from "../assets/tableData";

export const TRUCKS_TABLE_FIELDS = [
  {
    dataName: "Unit Number",
    dataKey: "unit_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "truck",
    searchable: true,
  },
  {
    dataName: "Plate Number",
    dataKey: "truck_license_plates.plate_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "truck",
    searchable: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: TRUCK_STATUS_CHOICES,
  },
  {
    dataName: "VIN",
    dataKey: "vin",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  {
    dataName: "Vehicle Type",
    dataKey: "vehicle_type",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: VEHICLE_TYPE_CHOICES,
  },
  {
    dataName: "Safety Expiry Date",
    dataKey: "truck_safety_docs.expiry_date",
    sort: true,
    show: true,
    date: true,
    checkDate: true,
    isLink: true,
    linkField: "truck_safety_docs.file",
  },
  {
    dataName: "Terminal",
    dataKey: "terminal",
    sort: true,
    show: true,
    date: false,
    type: "enum",
    values: TERMINAL_CHOICES,
  },
  {
    dataName: "Remarks",
    dataKey: "remarks",
    sort: true,
    show: true,
    date: false,
  },
];
