import { VIOLATION_STATUS_CHOICES } from "../assets/tableData";

export const VIOLATIONS_TABLE = [
  {
    dataName: "Violation ID",
    dataKey: "id",
    sort: true,
    show: false,
    date: false,
    searchable: true,
  },
  {
    dataName: "Violation Number",
    dataKey: "violation_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "violation",
  },
  {
    dataName: "Driver Id",
    dataKey: "driver_id",
    accessKey: "main_driver_id",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
  },
  {
    dataName: "Truck Unit Number",
    dataKey: "truck_id",
    accessKey: "truck",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "truck",
  },
  {
    dataName: "Date and Time of Violation",
    dataKey: "date_time",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: VIOLATION_STATUS_CHOICES,
  },
  {
    dataName: "Assigned To",
    dataKey: "assigned_to",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
  // {
  //   dataName: "Location",
  //   dataKey: "location",
  //   sort: true,
  //   show: true,
  //   date: false,
  // },
  {
    dataName: "Violation Details",
    dataKey: "violation_details",
    sort: true,
    show: true,
    date: false,
  },
];
