import { TERMINAL_CHOICES, WCB_STATUS_CHOICES } from "../assets/tableData";

export const WCB_TABLE = [
  {
    dataName: "WCB ID",
    dataKey: "id",
    sort: true,
    show: false,
    date: false,
    searchable: true,
  },
  {
    dataName: "4Tracks Claim #",
    dataKey: "claim_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "wcb",
  },
  {
    dataName: "WCB Claim #",
    dataKey: "wcb_claim_number",
    accessKey: "id",
    sort: true,
    show: true,
    date: false,
    searchable: true,
    isLink: true,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "wcb",
  },
  {
    dataName: "Status",
    dataKey: "status",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: WCB_STATUS_CHOICES,
  },
  {
    dataName: "Driver Id",
    dataKey: "driver_id",
    accessKey: "main_driver_id",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "driver",
  },
  {
    dataName: "Employee Id",
    dataKey: "employee_id",
    accessKey: "main_employee_id",
    sort: true,
    show: true,
    date: false,
    linkHandler: "showInfoCard",
    linkHandlerTarget: "employee",
  },
  {
    dataName: "Incident Details",
    dataKey: "incident_details",
    sort: true,
    show: true,
    date: false,
  },
  {
    dataName: "Remarks",
    dataKey: "remarks",
    sort: true,
    show: true,
    date: false,
  },
  {
    dataName: "Province",
    dataKey: "province",
    sort: true,
    show: true,
    date: false,
    filterable: true,
    type: "enum",
    values: TERMINAL_CHOICES,
  },
  {
    dataName: "Date and Time of Incident",
    dataKey: "date_time",
    sort: true,
    show: true,
    date: true,
  },
  {
    dataName: "Assigned To",
    dataKey: "assigned_to",
    sort: true,
    show: true,
    date: false,
    searchable: true,
  },
];
