import { CANADIAN_PROVINCES } from "@/config/clientData";

/**
 * WCB Claim Create Form Configuration
 *
 * Configuration for creating new WCB claims
 * Based on Prisma WcbClaim model
 *
 * Required fields: entityId (employee), incidentDate, province, incidentDetails
 * Claim number auto-generated if not provided
 * Default status: "new"
 */

// Injury severity options
const INJURY_SEVERITY_OPTIONS = {
  minor: 'Minor',
  moderate: 'Moderate',
  serious: 'Serious',
  critical: 'Critical',
};

// Entity type options for WCB claims
const ENTITY_TYPE_OPTIONS = {
  employees: 'Office Employee',
  // production_employees: 'Production Employee', // TODO: Uncomment when production employees are implemented
  // contractors: 'Contractor', // TODO: Uncomment when contractors are implemented
};

// Map entity types to API endpoints
const ENTITY_API_ENDPOINTS = {
  employees: '/api/v1/employees',
  production_employees: '/api/v1/production_employees',
  contractors: '/api/v1/contractors',
};

export const WCB_CLAIM_CREATE_FORM_CONFIG = {
  // No quick mode for WCB claims
  quickMode: {
    enabled: false,
  },

  fields: [
    // ========================================
    // Entity Selection Section
    // ========================================
    {
      key: "entityType",
      label: "Employee Type",
      type: "select",
      required: true,
      fullWidth: true,
      options: ENTITY_TYPE_OPTIONS,
      helperText: "Select the type of employee this claim is for",
    },

    {
      key: "entityId",
      label: "Select Employee",
      type: "entity-select",
      required: true,
      fullWidth: true,
      entityTypeField: "entityType", // Watch this field to determine which API to use
      entityTypeLabel: "employee type",
      apiEndpoint: (entityType) => ENTITY_API_ENDPOINTS[entityType] || '/api/v1/employees',
      displayFormat: (entity) => {
        // Format: "FirstName LastName (EmployeeID)" or "FirstName LastName (Email)" as fallback
        const name = `${entity.firstName || ''} ${entity.lastName || ''}`.trim();
        const identifier = entity.employeeId || entity.email || entity.id;
        return identifier ? `${name} (${identifier})` : name;
      },
      valueField: "id",
      placeholder: "Search and select employee...",
      emptyText: "No employees found.",
      helperText: "Select which employee this WCB claim is for",
    },

    // ========================================
    // Claim Information Section
    // ========================================
    // Note: claimNumber is auto-generated by the backend, no need to show it in the form

    // ========================================
    // Incident Details Section
    // ========================================
    {
      key: "incidentDate",
      label: "Incident Date & Time",
      type: "datetime",
      required: true,
      dateRange: { start: 'current-730', end: 'current' }, // Last 2 years to today
      helperText: "When did the incident occur?",
    },
    {
      key: "province",
      label: "Province/Territory",
      type: "select",
      required: true,
      options: CANADIAN_PROVINCES,
      helperText: "Where did the incident occur?",
    },
    {
      key: "location",
      label: "Specific Location",
      type: "text",
      required: false,
      placeholder: "e.g., Shop Bay 3, Highway 2 North, Office",
    },
    {
      key: "incidentDetails",
      label: "Incident Description",
      type: "textarea",
      required: true,
      rows: 4,
      placeholder: "Describe what happened, how the injury occurred, and any relevant details...",
      helperText: "Provide a detailed description of the incident",
    },

    // ========================================
    // Injury Details Section
    // ========================================
    {
      key: "injuryType",
      label: "Type of Injury",
      type: "text",
      required: false,
      placeholder: "e.g., Back strain, Laceration, Fracture, Concussion",
    },
    {
      key: "bodyPartAffected",
      label: "Body Part Affected",
      type: "text",
      required: false,
      placeholder: "e.g., Lower back, Right hand, Left knee, Head",
    },
    {
      key: "severityLevel",
      label: "Injury Severity",
      type: "select",
      required: false,
      options: INJURY_SEVERITY_OPTIONS,
    },

    // ========================================
    // Medical Information Section
    // ========================================
    {
      key: "reportedToDoctor",
      label: "Reported to Doctor",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      key: "firstContactDate",
      label: "First Medical Contact Date",
      type: "date",
      required: false,
      dateRange: { start: 'current-730', end: 'current' },
      helperText: "When was the first medical consultation?",
    },
    {
      key: "doctorName",
      label: "Doctor/Physician Name",
      type: "text",
      required: false,
      placeholder: "Dr. Smith",
    },
    {
      key: "doctorPhone",
      label: "Doctor Phone Number",
      type: "phone",
      required: false,
      placeholder: "+1 (555) 123-4567",
    },
    {
      key: "medicalFacility",
      label: "Medical Facility",
      type: "text",
      required: false,
      placeholder: "Hospital, clinic, or medical center name",
    },

    // ========================================
    // Return to Work Section
    // ========================================
    {
      key: "expectedReturnDate",
      label: "Expected Return to Work Date",
      type: "date",
      required: false,
      dateRange: { start: 'current', end: 'current+730' }, // Today to 2 years future
    },
    {
      key: "lostTimeDays",
      label: "Estimated Lost Time (Days)",
      type: "number",
      required: false,
      placeholder: "0",
      min: 0,
    },

    // ========================================
    // Notes Section
    // ========================================
    {
      key: "statusNote",
      label: "Status Note",
      type: "textarea",
      required: false,
      rows: 3,
      placeholder: "Current status or progress notes...",
    },
    {
      key: "remarksComments",
      label: "Additional Remarks",
      type: "textarea",
      required: false,
      rows: 3,
      placeholder: "Any additional comments or information...",
    },
  ],
};

export default WCB_CLAIM_CREATE_FORM_CONFIG;
