const dispatch = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_DISPATCH;
const safety = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_SAFETY;
const recruiting = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_RECRUITING;
const payroll = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_PAYROLL;
const payrollManager =
  process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_PAYROLL_MANAGER;
const planner = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_PLANNER;
const shop = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_SHOP;
const admin = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_ADMIN;
const portalHr = process.env.NEXT_PUBLIC_AZURE_ROLE_PORTAL_HR;

export const securedApiMapping = {
  "activity-history": [
    safety,
    recruiting,
    payroll,
    payrollManager,
    admin,
    portalHr,
  ],
  "add-rates": [safety, recruiting, payroll, payrollManager, admin, portalHr],
  "get-active-trucks": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-attendance-data": [admin, payroll, payrollManager],
  "get-claims": [safety, shop, admin],
  "get-driver-buttons-settings": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-driver-data": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-driver-log": [
    safety,
    recruiting,
    payroll,
    payrollManager,
    admin,
    portalHr,
  ],
  "get-driver-report-data": [safety, shop, admin],
  "get-driver-report-pdf": [safety, shop, admin],
  "get-driver-reports": [safety, shop, admin],
  "get-driver-reports-list": [
    safety,
    shop,
    admin,
    recruiting,
    payroll,
    payrollManager,
    portalHr,
  ],
  "get-driver-status-settings": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-drivers-recruiting": [
    safety,
    recruiting,
    payroll,
    payrollManager,
    admin,
    portalHr,
  ],
  "get-drivers-report": [
    safety,
    recruiting,
    payroll,
    payrollManager,
    admin,
    portalHr,
  ],
  "get-drivers-safety": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-drivers-to-be-reviewed": [safety, admin],
  "get-employee-buttons-settings": [admin, payroll, payrollManager, portalHr],
  "get-employee-card-pdf": [admin, payroll, payrollManager, portalHr],
  "get-employee-data": [admin, payroll, payrollManager, portalHr],
  "get-employee-log": [admin, payroll, payrollManager, portalHr],
  "get-employee-status-settings": [admin, payroll, payrollManager, portalHr],
  "get-equipment": [safety, shop, admin],
  "get-equipment-data": [safety, shop, admin],
  "get-equipment-status-settings": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-expiring-documents-drivers": [safety, admin],
  "get-fuel-quarterly": [safety, admin],
  "get-fuel-transactions": [safety, admin],
  "get-hired-drivers": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-hired-employees": [
    admin,
    payroll,
    recruiting,
    payrollManager,
    safety,
    portalHr,
  ],
  "get-incident-data": [safety, admin],
  "get-incidents": [safety, admin],
  "get-incidents-list": [safety, admin],
  "get-inspections": [safety, admin],
  "get-main-dashboard": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-office-employees": [admin, payroll, payrollManager, portalHr],
  "get-owner-operators": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-payroll-report": [admin, payrollManager],
  "get-tickets": [safety, admin],
  "get-truck-data": [safety, shop, admin, planner],
  "get-truck-status-settings": [
    dispatch,
    safety,
    recruiting,
    payroll,
    payrollManager,
    planner,
    shop,
    admin,
    portalHr,
  ],
  "get-trucks": [safety, shop, admin, planner],
  "get-trucks-table": [safety, shop, admin, planner],
  "get-violation-data": [safety, admin],
  "get-violations": [safety, admin],
  "get-violations-list": [safety, admin],
  "get-wcb-claims": [safety, admin],
  "get-wcb-data": [safety, admin],
  "get-wcb-list": [safety, admin],
  "save-attendance-data": [admin, payroll, payrollManager],
  "send-incident-photos": [safety, shop, admin],
  "send-violation-photos": [safety, shop, admin],
  "update-employee": [admin, payroll, payrollManager, portalHr],
  "update-file": [
    safety,
    planner,
    recruiting,
    payroll,
    payrollManager,
    admin,
    portalHr,
  ],
  "update-file-employee": [admin, payroll, payrollManager, portalHr],
  "update-incidents-log": [safety, admin],
  "update-seals": [safety, admin, planner],
  "update-violations-log": [safety, admin],
  "upload-driver-data": [
    safety,
    recruiting,
    payroll,
    payrollManager,
    admin,
    planner,
    portalHr,
  ],
  "upload-employee-data": [admin, payroll, payrollManager, portalHr],
  "upload-equipment-data": [safety, admin],
  "upload-fuel-report": [safety, admin],
  "upload-truck-data": [safety, admin, planner],
};
